export const CATEGORIES_TECH = [
    "None",
    "Mockup Green Screen", 
    "Mockup White Screen",
    "Mockup Black Screen", 
    "Polaroid Green Screen", 
    "Polaroid White Screen", 
    "Polaroid Black Screen", 
    "Koran Green Screen",
    "Koran White Screen",
    "Koran Black Screen", 
    "Objek dgn Latar Belakang Putih",
    "Objek dgn Latar Belakang Hijau",
    "Objek dgn Latar Belakang Hitam",
    "Template Background Hijau",
    "Template Background Putih",
    "Template Background Hitam",
    "Mockup papan kayu",
    "Balok kayu",
    "Kotak kardus",
    "Abstrak Flat Background"
];

export const CATEGORIES_STYLE = [
    "None",
    "--- 1. Foto Realistis ---",
    "Light Leaks & Lens Flare",
    "Dust & Scratches",
    "--- 2. Ilustrasi Vektor ---",
    "Flat Design",
    "Corporate Memphis (Alegria)",
    "Hand-Drawn / Doodle",
    "Pop Art / Comic Style",
    "Vintage Travel Poster & Stamp Style",
    "Abstract & Fluid Design",
    "Line Art / Monoline",
    "Isometric Vector",
    "Geometric",
    "Siluet (Silhouette)",
    "Stiker",
    "Pixel Art",
    "Artistic Travel-Style Vector",
    "Mascot & Character Design",
    "Lettering & Typography Vector",
    "--- 3. Gambar 3D ---",
    "3D Abstract Geometric & Textured Backgrounds",
    "Cutaway / Cross-Section 3D",
    "3D Typography / Lettering",
    "Product Commercial Rendering",
    "Medical & Scientific 3D",
    "3D Isometric Infographics",
    "Low Poly",
    "High Poly / Photorealistic",
    "Stylized",
    "Voxel Art",
    "3D Mockups",
    "Architectural Visualization (Archviz) & Interior 3D",
    "Cel Shading / Toon Shading",
    "Clay Render / Claymation Style",
    "3D Environment / Level Design",
    "Procedural / Fractal 3D",
    "--- 4. Pattern (Pola) ---",
    "Seamless Pattern",
    "Memphis Style Pattern",
    "Terrazzo",
    "Tribal / Ethnic",
    "Tartan / Plaid",
    "Polka Dot",
    "Argyle",
    "Camouflage (Camo)",
    "Floral & Botanical",
    "Gingham & Checkered",
    "Abstract Pattern",
    "Damask / Ornate",
    "Toile",
    "Houndstooth",
    "Paisley",
    "Chevron & Herringbone",
    "Animal Print",
    "Batik & Ikat",
    "Monogram Pattern",
    "--- 5. [Icon] ---",
    "Line / Stroke Icons",
    "Line / Stroke Icons (Putus-putus)",
    "Glyph Flat Vector Icon",
    "Duocolor Line Icons",
    "Dark Mode Line Art / Glowing Wireframe Icon",
    "Duotone Icons",
    "Filled Outline Vector",
    "Infographic Title Ribbons & UI Banners",
    "Glossy / Skeuomorphic UI Elements",
    "Flat Icons",
    "Hand-Drawn / Sketched Icons",
    "Gradient / Vibrant Icons",
    "Claymorphism",
    "Material Design / System Icons",
    "--- 6. [Logo] ---",
    "3D / Volumetric Logo",
    "Pictorial Mark / Brand Mark",
    "Emblem / Badge",
    "Minimalist / Line Art Logo",
    "Negative Space Logo",
    "Dynamic Logo",
    "Hand-Drawn / Artisan Logo",
    "--- 7. Tekstur & Overlays ---",
    "Grunge / Distressed",
    "Paper & Canvas Textures",
    "Shadow Overlay",
    "Plastic Wrap / Cellophane",
    "Smoke, Fog & Cloud",
    "Glass, Raindrops & Condensation",
    "Wood Grain & Timber",
    "Fabric & Textile",
    "--- 8. Sketsa Tradisional & Tinta ---",
    "Hatching & Cross-Hatching",
    "Stippling / Pointillism",
    "Graphite & Charcoal",
    "Ink Wash",
    "Scratchboard",
    "Continuous Line / Contour Drawing",
    "Scumbling / Scribbling",
    "Sanguine / Red Chalk",
    "Ballpoint Pen Art",
    "Woodcut / Linocut Style",
    "Sumi-e",
    "--- 9. Isolated Watercolor Elements ---",
    "Watercolor Swashes & Brush Strokes",
    "Watercolor Splashes & Splatters",
    "Watercolor Stains & Blobs",
    "Watercolor Cosmetic & Lifestyle Objects",
    "Watercolor Floral & Botanical Cuts",
    "--- 10. Lukisan Konvensional / Seni Halus ---",
    "Transparent Watercolor",
    "Gouache",
    "Impasto",
    "Alla Prima",
    "Plein Air",
    "Oil Painting",
    "Acrylic Painting",
    "Fresco",
    "Tempera (Egg Tempera)",
    "Encaustic (Hot Wax Painting)",
    "Sfumato",
    "Chiaroscuro / Tenebrism",
    "--- 11. Matte Painting & Photobashing ---",
    "Set Extension",
    "Sci-Fi & Cyberpunk Environments",
    "Post-Apocalyptic Ruins",
    "Fantasy World-Building",
    "Creature / Character Photobashing",
    "Double Exposure",
    "Historical & Period Environments",
    "Space & Cosmic Scapes",
    "Surrealism & Dreamscapes",
    "Vehicle & Hard-Surface Photobashing",
    "Underwater Worlds",
    "Natural Disasters & Extreme Weather",
    "2.5D Camera Projection (Camera Mapping)",
    "--- 12. Mockup Produk & Desain ---",
    "PSD Mockup Templates",
    "Printable Stationery & Digital Planner Pages",
    "Device & Technology Mockups",
    "Apparel & Fashion Mockups",
    "Packaging Mockups",
    "Print & Editorial Mockups",
    "Branding / Stationery Kits",
    "Signage & Outdoor Mockups",
    "Home Decor & Wall Art Mockups",
    "Vehicle & Car Wrap Mockups",
    "Merchandise & Promotional Mockups",
    "Event & Exhibition Mockups",
    "Textile & Fabric Mockups",
    "UI/UX & Web Presentation Mockups",
    "--- 13. Background Design ---",
    "Decorative Corner Borders & Oriental Ornaments",
    "Islamic Background & Certificate Templates",
    "Mesh Gradient",
    "Holographic / Iridescent",
    "Soft Pastel Gradients",
    "Liquid / Fluid Waves",
    "Glassmorphism Background",
    "Abstract 3D Shapes",
    "Low Poly Background",
    "Particle & Network Nodes",
    "Cyber Grid / Wireframe",
    "Paper & Cardboard Texture",
    "Marble & Stone Texture",
    "Foil & Metallic Texture",
    "Studio Podium / Pedestal",
    "Soft Grain / Noise Surface",
    "Neumorphic Surface",
    "Micro-Patterns / Dotted",
    "Halftone Waves",
    "Geometric Abstract Background",
    "Grunge & Paint Strokes Abstract",
    "Light Trails & Bokeh"
];

export const STYLE_DESCRIPTIONS = {
    // 1. Foto Realistis
    "Light Leaks & Lens Flare": "Pendaran cahaya bocor (biasanya bernuansa merah, oranye, atau pelangi) dan silau lensa kamera. Digunakan untuk menciptakan nuansa emosional, hangat, atau sinematik ala film analog.",
    "Dust & Scratches": "Lapisan transparan berisi bintik-bintik debu dan goresan halus untuk menciptakan estetika rekaman seluloid zaman dahulu atau foto lama.",
    
    // 2. Ilustrasi Vektor
    "Flat Design": "Gaya minimalis dengan warna solid tanpa bayangan atau gradien kompleks, sangat efisien untuk desain antarmuka dan infografis.",
    "Corporate Memphis (Alegria)": "Gaya ilustrasi karakter yang sangat mendominasi desain UI/UX dan web modern. Ciri khasnya adalah karakter dengan proporsi tubuh yang dilebih-lebihkan dan warna-warna cerah.",
    "Hand-Drawn / Doodle": "Vektor yang sengaja direkayasa agar terlihat seperti coretan tangan kasar menggunakan pena atau kuas digital.",
    "Pop Art / Comic Style": "Menggunakan titik-titik halftone, garis luar yang tebal, dan warna primer yang mencolok ala buku komik retro.",
    "Vintage Travel Poster & Stamp Style": "Gaya retro klasik yang meniru estetika poster perjalanan zaman dulu atau desain perangko vintage.",
    "Abstract & Fluid Design": "Komposisi vektor yang mengandalkan bentuk-bentuk organik, melengkung (liquid/fluid), dan abstrak.",
    "Line Art / Monoline": "Style: Monoline Vector. Minimalist continuous one-line drawing, pure black line art, simple monoline outline, elegant thin black stroke, consistent line weight. Strictly no fills, strictly no colors.",
    "Isometric Vector": "Penggambaran elemen 2D dengan sudut pandang miring (biasanya 30 derajat) untuk menciptakan ilusi ruang tiga dimensi.",
    "Geometric": "Karya visual yang murni dibangun dari perpaduan bentuk-bentuk dasar seperti lingkaran, persegi, dan segitiga.",
    "Siluet (Silhouette)": "Fokus pada garis luar objek dengan warna solid (biasanya hitam atau monokrom).",
    "Stiker": "Seni digital bergaya stiker dengan batas tepi yang tegas (die-cut border).",
    "Pixel Art": "Classic 8-bit pixel art style, retro video game aesthetic, sharp square pixels.",
    "Artistic Travel-Style Vector": "Ilustrasi pemandangan dengan pendekatan sapuan digital artistik.",
    "Mascot & Character Design": "Ilustrasi vektor yang berfokus khusus pada pembuatan karakter maskot.",
    "Lettering & Typography Vector": "Fokus pada seni tata huruf yang digambar dan diolah secara manual.",
    
    // 3. Gambar 3D
    "3D Abstract Geometric & Textured Backgrounds": "3D Layered & Textured Backgrounds. Permainan kedalaman ruang (depth) melalui tumpukan bentuk geometris yang saling overlapping. Pencahayaan studio sangat realistis menciptakan bayangan jatuh (soft drop shadows) serta penekanan pada material fisik nyata (wood grain, matte plastic).",
    "Cutaway / Cross-Section 3D": "Gaya gambar 3D yang memotong sebagian objek untuk memperlihatkan struktur mekanis.",
    "3D Typography / Lettering": "Seni merancang teks dan huruf dalam ruang 3 dimensi.",
    "Product Commercial Rendering": "Ini adalah render produk akhir yang sangat detail dengan pencahayaan studio khusus untuk iklan high-end. STRICT MANDATE: Buat tampilan produk polosan murni tanpa penambahan teks, huruf, angka, atau embel-embel merk brand (strictly no branding, no text labels).",
    "Medical & Scientific 3D": "Render yang berfokus pada visualisasi mikroskopis, sel, atau anatomi.",
    "3D Isometric Infographics": "Render 3D dengan sudut pandang isometrik untuk visualisasi data.",
    "Low Poly": "Model 3D yang sengaja menggunakan jumlah poligon sangat sedikit.",
    "High Poly / Photorealistic": "Model 3D dengan jutaan poligon dan tekstur material yang sangat akurat.",
    "Stylized": "Model 3D yang proporsi dan teksturnya sengaja diubah menjadi lebih ekspresif.",
    "Voxel Art": "Seni 3D yang dibangun menggunakan blok-blok kubus.",
    "3D Mockups": "Render ruang, podium, atau objek kosong yang siap disisipi desain.",
    "Architectural Visualization (Archviz) & Interior 3D": "Visualisasi realistis dari eksterior bangunan atau desain interior.",
    "Cel Shading / Toon Shading": "Gaya render 3D yang sengaja dimanipulasi agar terlihat seperti anime.",
    "Clay Render / Claymation Style": "Gaya render 3D yang meniru tekstur dan pencahayaan tanah liat.",
    "3D Environment / Level Design": "Berfokus pada penciptaan latar belakang, pemandangan alam, atau tata kota.",
    "Procedural / Fractal 3D": "Gambar 3D yang dihasilkan secara otomatis melalui rumus matematika.",
    
    // 4. Pattern (Pola)
    "Seamless Pattern": "Pola yang didesain agar sisi kiri menyambung ke kanan tanpa terlihat batas patahannya.",
    "Memphis Style Pattern": "Pola era 80-an yang menggunakan warna-warna kontras tinggi.",
    "Terrazzo": "Meniru tekstur lantai terrazzo dengan serpihan-serpihan asimetris.",
    "Tribal / Ethnic": "Pola yang terinspirasi dari motif tenun tradisional.",
    "Tartan / Plaid": "Pola kotak-kotak persilangan garis vertikal dan horizontal.",
    "Polka Dot": "Pola sederhana berupa lingkaran-lingkaran padat.",
    "Argyle": "Pola yang terdiri dari susunan bentuk intan (belah ketupat).",
    "Camouflage (Camo)": "Pola loreng organik tak beraturan.",
    "Floral & Botanical": "Pola organik yang terdiri dari bunga dan dedaunan.",
    "Gingham & Checkered": "Gingham adalah pola persilangan garis warna dan putih. Checkered adalah pola kotak-kotak padat. STRICT MANDATE: Pola murni, strictly no human figures, no people.",
    "Abstract Pattern": "Pola bebas yang tidak menggambarkan objek nyata secara langsung.",
    "Damask / Ornate": "Pola dekoratif tradisional yang sangat rumit dan elegan.",
    "Toile": "Pola klasik bergaya lukisan Eropa klasik.",
    "Houndstooth": "Pola kotak-kotak abstrak dua warna dengan tepi bergerigi.",
    "Paisley": "Pola ornamental klasik bentuk tetesan air melengkung.",
    "Chevron & Herringbone": "Pola zig-zag atau susunan tulang ikan.",
    "Animal Print": "Pola organik yang meniru corak alami kulit hewan.",
    "Batik & Ikat": "Pola tradisional berbasis teknik pewarnaan kain.",
    "Monogram Pattern": "Pola yang disusun dari pengulangan inisial huruf.",

    // 5. [Icon]
    "Line / Stroke Icons": "Bold thick black line art icon, minimalist ui icon style, uniform heavy stroke weight, perfectly flat, strictly no fills, clean white background.",
    "Line / Stroke Icons (Putus-putus)": "Bold dashed line art icon, dotted stroke outline, minimalist ui icon style, uniform heavy dashed stroke weight, perfectly flat, strictly no fills.",
    "Glyph Flat Vector Icon": "glyph flat vector icon of [objek], solid black fill, strictly no outlines, minimalist ui icon style, perfectly flat 2D vector design, clean edges, strictly no gradients, strictly no shadows, pure white background, perfectly centered, isolated.",
    "Duocolor Line Icons": "Two-tone duocolor minimalist line art icon, strictly uniform stroke weight, rounded caps and joins, exactly two colors used (one main, one accent), strictly no solid color fills.",
    "Dark Mode Line Art / Glowing Wireframe Icon": "Glowing neon wireframe icon, thin bright line art on a pure pitch black background, subtle light emission glow effect, dark mode UI aesthetic, high-tech elegant look, isolated on pure black.",
    "Duotone Icons": "Menggunakan perpaduan dua warna kontras (warna utama dan opasitas rendah).",
    "Filled Outline Vector": "Cartoonish filled outline vector illustration, solid flat vibrant colors inside, surrounded by bold thick black outlines, no gradients, flat 2D style.",
    "Infographic Title Ribbons & UI Banners": "Vector flat design banner ribbons, lower thirds UI elements, numbered circles on the edge, strict empty blank space inside the ribbon for text placement, strictly no actual text.",
    "Glossy / Skeuomorphic UI Elements": "Web 2.0 aesthetic, heavy Skeuomorphism UI element, glossy 3D plastic/glass effect, heavy inner glow, drop shadows, highly polished reflective surface.",
    "Flat Icons": "Gaya desain ikon dua dimensi yang sangat minimalis.",
    "Hand-Drawn / Sketched Icons": "Ikon bergaya coretan tangan manual atau doodle.",
    "Gradient / Vibrant Icons": "Ikon berbasis vektor datar namun memanfaatkan transisi gradien warna cerah.",
    "Claymorphism": "Ikon seolah-olah terbuat dari tanah liat lembut mengembang.",
    "Material Design / System Icons": "Ikon berpedoman ketat berbasis grid murni untuk fungsionalitas.",

    // 6. [Logo]
    "3D / Volumetric Logo": "Logo ilusi ruang 3 dimensi. Pencahayaan realistis, gradien. STRICTLY NO TEXT.",
    "Pictorial Mark / Brand Mark": "Logo berupa ikon atau simbol grafis tanpa teks. STRICTLY NO TEXT.",
    "Emblem / Badge": "Simbol di dalam bingkai lencana. STRICTLY BLANK TEXT AREA.",
    "Minimalist / Line Art Logo": "Logo modern murni dari ketebalan garis seragam. STRICTLY NO TEXT.",
    "Negative Space Logo": "Desain siluet cerdas menggunakan area kosong. STRICTLY NO TEXT.",
    "Dynamic Logo": "Logo adaptif/dinamis dengan kerangka dasar konsisten. STRICTLY NO TEXT.",
    "Hand-Drawn / Artisan Logo": "Gaya coretan tangan manual. STRICTLY BLANK TEXT AREA.",

    // 7. Tekstur & Overlays
    "Grunge / Distressed": "Efek permukaan kotor, berkarat, atau tergores.",
    "Paper & Canvas Textures": "Kertas kusut, kardus, atau serat kanvas.",
    "Shadow Overlay": "Soft diffused shadow overlay with gentle transparency, subtle light-grey cast shadow, strictly pure solid white background.",
    "Plastic Wrap / Cellophane": "Tekstur meniru pantulan pembungkus plastik bening.",
    "Smoke, Fog & Cloud": "Overlay partikel asap atau awan transparan.",
    "Glass, Raindrops & Condensation": "Overlay efek kaca berembun atau tetesan air hujan.",
    "Wood Grain & Timber": "Tekstur organik serat alami kayu.",
    "Fabric & Textile": "Tekstur jalinan benang atau kain rajutan.",

    // 8. Sketsa Tradisional & Tinta
    "Hatching & Cross-Hatching": "Kumpulan garis sejajar atau saling menyilang rapat.",
    "Stippling / Pointillism": "Membangun bayangan murni menggunakan jutaan titik kecil pena.",
    "Graphite & Charcoal": "Transisi bayangan mulus arang untuk chiaroscuro dramatis.",
    "Ink Wash": "Kombinasi garis pena tinta tegas dengan sapuan kuas basah.",
    "Scratchboard": "Teknik menggambar terbalik pada papan berlapis tinta hitam.",
    "Continuous Line / Contour Drawing": "Menggambar dengan satu garis lurus tak pernah terputus.",
    "Scumbling / Scribbling": "Coretan melingkar acak yang saling menumpuk.",
    "Sanguine / Red Chalk": "Sketsa menggunakan kapur merah kecokelatan.",
    "Ballpoint Pen Art": "Sketsa fotorealistik murni tinta pulpen.",
    "Woodcut / Linocut Style": "Garis hitam putih kontras tinggi ala cetakan kayu kuno.",
    "Sumi-e": "Seni lukis kuas tinta Asia Timur minimalis.",

    // 9. Isolated Watercolor Elements
    "Watercolor Swashes & Brush Strokes": "Sapuan kuas tebal atau pita warna (ribbon) dengan ujung tekstur kuas jelas.",
    "Watercolor Splashes & Splatters": "Cipratan cat tidak beraturan dan menyebar.",
    "Watercolor Stains & Blobs": "Noda atau bercak membulat dan tenang.",
    "Watercolor Cosmetic & Lifestyle Objects": "Objek fisik dunia nyata diilustrasikan gaya sapuan cat air fluid.",
    "Watercolor Floral & Botanical Cuts": "Elemen individual kelopak bunga atau dedaunan.",

    // 10. Lukisan Konvensional / Seni Halus
    "Transparent Watercolor": "Cat air klasik tembus pandang (wash).",
    "Gouache": "Medium berbasis air bersifat opaque (menutup) hasil matte.",
    "Impasto": "Cat diaplikasikan sangat tebal dengan pisau palet bertekstur timbul.",
    "Alla Prima": "Lukisan cat minyak kilat basah-di-atas-basah.",
    "Plein Air": "Penangkapan pemandangan alam langsung di luar ruangan.",
    "Oil Painting": "Medium lukis klasik transisi warna sangat halus.",
    "Acrylic Painting": "Warna solid kontemporer cepat kering.",
    "Fresco": "Melukis mural klasik di atas plester dinding basah.",
    "Tempera (Egg Tempera)": "Teknik kuno warna awet berbasis kuning telur.",
    "Encaustic (Hot Wax Painting)": "Teknik kuno lilin lebah dipanaskan.",
    "Sfumato": "Blending melembutkan transisi warna tanpa garis tegas (ala Da Vinci).",
    "Chiaroscuro / Tenebrism": "Pencahayaan dramatis kontras cahaya terang vs gelap gulita.",

    // 11. Matte Painting & Photobashing
    "Set Extension": "Latar belakang penyambung set fisik di dunia nyata untuk VFX.",
    "Sci-Fi & Cyberpunk Environments": "Desain kota masa depan atau pesawat luar angkasa dari tekstur foto mekanis.",
    "Post-Apocalyptic Ruins": "Tumpukan kehancuran pada foto bangunan modern.",
    "Fantasy World-Building": "Lanskap kerajaan fiktif manipilasi foto arsitektur kuno.",
    "Creature / Character Photobashing": "Konsep karakter tempel tekstur kulit/logam.",
    "Double Exposure": "Siluet objek berpadu dengan pemandangan alam sekunder.",
    "Historical & Period Environments": "Rekonstruksi lanskap peradaban kuno.",
    "Space & Cosmic Scapes": "Pemandangan kosmik luar angkasa murni.",
    "Surrealism & Dreamscapes": "Lingkungan surealis arsitektur terbalik.",
    "Vehicle & Hard-Surface Photobashing": "Rancangan kendaraan dari potongan logam mekanis.",
    "Underwater Worlds": "Lingkungan bawah laut imersif.",
    "Natural Disasters & Extreme Weather": "Visualisasi cuaca ekstrem bencana alam.",
    "2.5D Camera Projection (Camera Mapping)": "Matte painting struktural terpisah layer untuk ilusi parallax.",

    // 12. Mockup Produk & Desain
    "PSD Mockup Templates": "Professional blank mockup, strictly empty surface, pure blank white label, perfectly plain, strictly no text, no logos, no branding, no graphic elements, studio lighting, isolated on a flat pure solid white background.",
    "Printable Stationery & Digital Planner Pages": "Functional ruled lines for writing, digital planner page layout, strictly blank header blocks, clean empty writing space, printable stationery layout, completely blank of written words.",
    "Device & Technology Mockups": "Layar smartphone/laptop kosong (solid/chroma-key). NO fake logos.",
    "Apparel & Fashion Mockups": "Permukaan kain kaos/hoodie murni kosong. NO text, NO existing branding.",
    "Packaging Mockups": "Mockup kemasan kotak/botol murni. NO text.",
    "Print & Editorial Mockups": "Buku/majalah lipatan kertas murni kosong. NO text.",
    "Branding / Stationery Kits": "Set identitas perusahaan murni kosong tertata rapi. NO text.",
    "Signage & Outdoor Mockups": "Papan reklame murni kosong. NO text.",
    "Home Decor & Wall Art Mockups": "Bingkai seni dinding/keramik di interior bersih kosong. NO text.",
    "Vehicle & Car Wrap Mockups": "Permukaan bodi kendaraan murni kosong untuk stiker.",
    "Merchandise & Promotional Mockups": "Visualisasi barang souvenir promosi kosong murni.",
    "Event & Exhibition Mockups": "Booth pameran, tenda, banner murni kosong.",
    "Textile & Fabric Mockups": "Visualisasi kain tekstil murni kosong.",
    "UI/UX & Web Presentation Mockups": "Kerangka presentasi antarmuka kosong.",

    // 13. Background Design
    "Decorative Corner Borders & Oriental Ornaments": "Strictly positioned at the corners of the canvas, framing the empty center, Oriental/Chinese traditional knots and cloud motifs, completely blank center space for layout.",
    "Islamic Background & Certificate Templates": "Islamic architecture, geometric patterns, strictly blank empty center space for text layout, certificate template composition, no real text.",
    "Mesh Gradient": "Abstract mesh gradient background. Massive empty copy space.",
    "Holographic / Iridescent": "Holographic and iridescent surface reflection. Massive empty copy space.",
    "Soft Pastel Gradients": "Soft pastel gradient background. Minimal contrast. Massive empty copy space.",
    "Liquid / Fluid Waves": "Liquid and fluid 3D waves background. Massive empty copy space.",
    "Glassmorphism Background": "Glassmorphism aesthetic frosted glass effect. Massive empty copy space.",
    "Abstract 3D Shapes": "Abstract 3D geometric shapes floating in empty space. Massive empty copy space.",
    "Low Poly Background": "Low poly geometric triangulated background. Massive empty copy space.",
    "Particle & Network Nodes": "Particle network nodes glowing dots lines. Massive empty copy space.",
    "Cyber Grid / Wireframe": "Cyber grid retro-futuristic grid perspective. Massive empty copy space.",
    "Paper & Cardboard Texture": "High resolution paper, cardboard texture background. Massive empty copy space.",
    "Marble & Stone Texture": "Elegant marble granite stone texture background. Massive empty copy space.",
    "Foil & Metallic Texture": "Crumpled gold metallic foil texture background. Massive empty copy space.",
    "Studio Podium / Pedestal": "Empty 3D studio podium pedestal stage. Massive empty copy space.",
    "Soft Grain / Noise Surface": "Soft grain noise surface aesthetic film background. Massive empty copy space.",
    "Neumorphic Surface": "Neumorphic aesthetic extruded debossed shapes. Massive empty copy space.",
    "Micro-Patterns / Dotted": "Micro-pattern dotted crosshatch texture background. Massive empty copy space.",
    "Halftone Waves": "Halftone dotted waves background gradient. Massive empty copy space.",
    "Geometric Abstract Background": "Komposisi geometris abstrak Bauhaus modern terstruktur. Massive empty copy space.",
    "Grunge & Paint Strokes Abstract": "Latar fisik organik cat splatter ekspresif. Massive empty copy space.",
    "Light Trails & Bokeh": "Manipulasi cahaya neon blur bokeh. Massive empty copy space."
};

export const ASPECT_RATIOS = ['1:1', '3:2', '2:3', '3:4', '1:4', '4:1', '4:3', '4:5', '5:4', '1:8', '8:1', '9:16', '16:9', '21:9', '9:21', '16:10', '10:16', '2:1', '1:2', '7:5', '5:7'];
export const RESOLUTIONS = ['Asli', '2K', '3K', '4K'];
export const FORMATS = ['jpg', 'png'];
